### ISSUE TITLE
Login from developer.oftrust.net fails

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#40]
# Describe the bug
Tried to login from developer.oftrust.net by clicking login button in navi. Resulted to 404 page. From there if I click the offered "main page" link which takes me to MyWorld I can login. 

# To Reproduce
1. Go to https://developer.oftrust.net
2. Click on 'login'
3. Fill in the credentials
34. See error

# Expected behavior

Here are two errors:
- Login fails
https://www.youtube.com/watch?v=U-KZqLf3x_M&feature=youtu.be

- Provided link "Go to main page" should not take me to MyWorld. Either take me back to platformoftrust.net or developer.oftrust.net depending of where the user came from

<img width="906" alt="Näyttökuva 2020-5-18 kello 8 22 34" src="https://user-images.githubusercontent.com/1927158/82177010-04929400-98e1-11ea-8283-15cecc564b6b.png">

# Environment (please complete the following information):
 - Device: Desktop
 - OS: iOS
 - Browser: FF
 - Version: 76.0.1 (64-bit)

**Comment by ralupopa** [comment]
landing page to a 404 after login is already reported internally.

**Comment by edanchenkov** [comment]
In this case it is because auth link is incorrectly generated and meant for old my world app `https://login-sandbox.oftrust.net/?grant_type=authorization&response_type=code&redirect_uri=https://world-sandbox.oftrust.net/api/exchangeToken&client_id=f773dafe-20c0-4a25-aa3e-9da0b81b9304&cancel_url=https://world-sandbox.oftrust.net&reset_password_success_url=https://world-sandbox.oftrust.net/api/login&state=eyJkIjogeyJyIjogImh0dHBzOi8vd29ybGQtc2FuZGJveC5vZnRydXN0Lm5ldC9hcGkvZXhjaGFuZ2VUb2tlbiIsICJ0cyI6IDE1ODI1Mjg3ODB9LCAiaCI6ICJlNDI3ODg0N2E3OWFiNWQxZmFlM2NiNTY5NGViNzc3ZjNiNTk2MjJiIn0=#sign-up`

So whoever is running https://developer.oftrust.net should implement proper auth https://developer.oftrust.net/guides/integrate-oauth-20-access-platform-trust-apis/ to their app.

But giving 404 error is also not good in this case, and as Raluca said, it should have been reported .

**Comment by Nazarah** [comment]
@kyyberi  forwarded this to the Engineering channel. They will investigate this.

**Comment by kyyberi** [comment]
If I ignite the login from Developer Portal, that is the place where I want to be redirected after login.

**Comment by Nazarah** [comment]
@kyyberi  fixed and deployed.
