### ISSUE TITLE
Link to join mailing list not working

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/collected-feedback#43]
# Describe the Pain in using this API

Link "Sign up for mailing list" in docs.oftrust.net is not working.  

<img width="862" alt="Näyttökuva 2020-5-28 kello 20 16 18" src="https://user-images.githubusercontent.com/1927158/83172369-24675a80-a120-11ea-96b7-51bde645ce4d.png">

Link is `https://developer.oftrust.net/#Help-us-achieve-the-perfect-flow-state` and correct is `https://developer.oftrust.net/#help-us-achieve-the-perfect-flow-state`

# Indicate the importance in number
(1. Critical, 2. Important, 3. Nice-to-have)

1. 

**Additional context**

**Comment by Nazarah** [comment]
@kyyberi I have an alternative suggestion. would it be ok if we give add a hyperlink for the HubSpot form for signing up for business or technical newsletter? because now, even if the link is clicked, in the developer portal, the user never gets scrolled down to the designated place.

**Comment by catalin-sbp** [comment]
We've fixed this issue, however, we've also recorded hyperlinks with anchors to docs.oftrust.net which did not work correctly due to the fact that the anchors are case-sensitive by default.

Our recommendation is to implement a generic client-side script which be added to all of the web apps in order to still scroll to the proper anchor independently of the casing. @kyyberi  How does this sound?

**Comment by kyyberi** [comment]
That depends on the amount of broken links now and anticipated amount in the future. Implementing code for misspelled links sounds like an overkill to me. Fix the links as they are found IMHO.

**Comment by Nazarah** [comment]
I am closing this issue as it has been fixed. Regarding to the concerns discussed here. I'll open a new issue and add the details there. That would be scheduled for implementation on August 2020.
