### ISSUE TITLE
Ontology Viewer | Identities MeasureAirHumidity and MeasureAirHumidityRH are listed but don't have page description

### ISSUE THREAD

**Issue by ralucaoanapopa** [PlatformOfTrust/collected-feedback#62]
## Tell us the importance in a number:
(1 --> Critical, 2 --> Important, 3 --> Nice to have)
2

# Are you reporting for a bug?

## Describe the bug
There are identities added which requires some updates to be able to see their details when access from ontology viewer.

## To Reproduce
![image](https://user-images.githubusercontent.com/22395549/98967697-76a50800-2515-11eb-9afe-ffddc3bd5c39.png)
Accessing identities from class hierarchy go to a 404 page

https://standards-ontotest.oftrust.net/v2/Vocabulary/MeasureAirHumidity
https://standards-ontotest.oftrust.net/v2/Vocabulary/MeasureAirHumidityRH

## Expected behavior
Be able to access these identities from ontology viewer

**Comment by ralupopa** [comment]
Closing this since it is updated on production, can access general, vocabulary, context, json schema data example of these 2:
https://standards.oftrust.net/v2/Context/Identity/Process/Measure/MeasureAirHumidity/MeasureAirHumidityRH/
https://standards.oftrust.net/v2/Context/Identity/Process/Measure/MeasureAirHumidity/
